# 1-4 TensorとPyTorch

In [1]:
import numpy as np
import torch

## 1.Tensorの作成

In [2]:
torch.tensor([0, 1, 2, 3])

tensor([0, 1, 2, 3])

torch.tensor()の場合は自動的に型がfloatになる

In [4]:
torch.Tensor([0, 1, 2, 3])

tensor([0., 1., 2., 3.])

In [3]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

### 形状だけを指定

In [5]:
torch.Tensor(2, 3)

tensor([[-2.1975e+07,  3.0830e-41, -2.1986e+07],
        [ 3.0830e-41,  1.1210e-43,  0.0000e+00]])

In [7]:
torch.Tensor(3)

tensor([-2.1991e+07,  3.0830e-41, -2.1967e+07])

### 連続

In [8]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape

In [10]:
torch.arange(6).reshape(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

## 2.Tensorと数値の四則演算

In [13]:
a = torch.arange(5)
a + 2

tensor([2, 3, 4, 5, 6])

In [14]:
a = np.arange(5)
a + 2

array([2, 3, 4, 5, 6])

## 3. Tensor同士の四則演算

In [16]:
a = torch.arange(6).reshape(2, 3)
b = a + 1

print(a)
print(b)

a * b

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[ 0,  2,  6],
        [12, 20, 30]])

## 4. tensor同士の行列計算

#### 内積：１次元どうしの行列積 dot, matmul

In [17]:
a0 = torch.tensor([1, 2, 3, 4])
a1 = torch.tensor([5, 6, 7, 8])

In [18]:
torch.dot(a0, a1)

tensor(70)

In [19]:
torch.matmul(a0, a1)

tensor(70)

#### 行列とベクトルの行列積　mv, matmul

In [20]:
a0 = torch.tensor([1, 2, 3, 4])
a1 = torch.arange(8).reshape(2, 4)

In [21]:
torch.mv(a1, a0)

tensor([20, 60])

In [22]:
torch.matmul(a1, a0)

tensor([20, 60])

#### 行列同士の行列積　mm, matmul

In [23]:
a0 = torch.arange(8).reshape(2, 4)
a1 = torch.arange(8).reshape(4, 2)

In [24]:
torch.mm(a0, a1)

tensor([[28, 34],
        [76, 98]])

In [25]:
torch.matmul(a0, a1)

tensor([[28, 34],
        [76, 98]])

## 5. Tensor同士のバッチの行列積

関数bmm 関数matmul

In [27]:
a0 = torch.arange(24).reshape(-1, 2, 4)
a0

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [28]:
a1 = torch.arange(24).reshape(-1, 4, 2)
a1

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

In [31]:
torch.bmm(a0, a1)

tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])

In [32]:
torch.matmul(a0, a1)

tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])

## 6.Tensorを扱う関数

In [33]:
a = torch.tensor([1, 2, 3])

In [34]:
torch.sin(a)

tensor([0.8415, 0.9093, 0.1411])

In [35]:
torch.log(a)

tensor([0.0000, 0.6931, 1.0986])

## 7. Tensorの型と型の変換

In [36]:
a0 = torch.tensor([1, 2, 3])

In [37]:
a0.dtype

torch.int64

In [38]:
a0.type()

'torch.LongTensor'

#### 理想の型を得るには？ <br><br>　①生成時にdtypeで型を指定する　<br>　②type()を使ってtensorの型を変換する

In [39]:
a0 = torch.tensor([1, 2, 3])
a0.type()

'torch.LongTensor'

In [40]:
a0 = torch.tensor([1, 2, 3], dtype=torch.float)
a0.type()

'torch.FloatTensor'

## 8. TensorとNumPy

numpy() または　from_numpy()

In [41]:
a0 = torch.tensor([1, 2, 3])
a0.dtype

torch.int64

In [43]:
b0 = a0.numpy()
b0.dtype

dtype('int64')

In [45]:
a1 = torch.from_numpy(b0)
a1.dtype

torch.int64

### 注意：配列tensorに微分の情報が付与されている時には、それをdetach()で切り離してから出ないとnumpy()を使えない

In [47]:
a = torch.tensor([1., ], requires_grad=True)
a.dtype

torch.float32

In [48]:
b = a.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [50]:
b = a.detach().numpy()
b.dtype

dtype('float32')

## 9. Tensorの結合

#### 縦に結合：cat()　横に結合：cat( , dim=1)

In [52]:
a = torch.zeros(6).reshape(2, 3)
b = torch.ones(6).reshape(2, 3)

In [53]:
torch.cat([a, b])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [54]:
torch.cat([a, b], dim=1)

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

#### 同じ形状の複数の配列をリストして、それをバッチにする：stack()

In [55]:
a = torch.zeros(6).reshape(2, 3)
b = torch.ones(6).reshape(2, 3)
c = b + 1

In [56]:
torch.stack([a, b, c])

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

## 10. Tensorの軸の操作

#### 軸の削除:squeeze()　１つだけの配列をバッチにする:unsqueeze()

In [57]:
a = torch.arange(6).reshape(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [58]:
a.unsqueeze(0)

tensor([[[0, 1, 2],
         [3, 4, 5]]])

#### 軸の入れ替え：permute()

In [59]:
a = torch.arange(12).reshape(2, 2, -1)
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [60]:
a.permute(2, 0, 1)

tensor([[[ 0,  3],
         [ 6,  9]],

        [[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]]])

## 11. Tensorと自動微分

#### 微分値を求める必要のあるtensorはrequires_gradという属性の値をTrueに設定する

In [61]:
import torch

def f(x1, x2, x3):
    return (x1 - 2*x2 - 1)**2 + (x2 * x3 - 1)**2 + 1


def f_grad(x1, x2, x3):
    z = f(x1, x2, x3)
    z.backward()
    return (x1.grad, x2.grad, x3.grad)



x1 = torch.tensor([1.], requires_grad=True)
x2 = torch.tensor([2.], requires_grad=True)
x3 = torch.tensor([3.], requires_grad=True)

for i in range(50):
    g1, g2, g3 = f_grad(x1, x2, x3)
    
    x1 = x1 - 0.1 * g1
    x2 = x1 - 0.1 * g2    
    x3 = x1 - 0.1 * g3
    
    x1 = x1.detach().requires_grad_(True)
    x2 = x2.detach().requires_grad_(True)    
    x3 = x3.detach().requires_grad_(True)    
    
    print('x = [{}, {}, {}], f = {}'.format(x1.item(), x2.item(), x3.item(), f(x1, x2, x3).item()))

x = [1.7999999523162842, -2.799999952316284, -0.20000004768371582], f = 42.153594970703125
x = [0.5199999809265137, 3.0623998641967773, 0.2736000418663025], f = 44.64966583251953
x = [1.840959906578064, -0.7920883893966675, 1.940259575843811], f = 13.31693172454834
x = [1.355932593345642, 3.3104195594787598, 0.9540495872497559], f = 44.90733337402344
x = [2.6089138984680176, -0.30887460708618164, 1.1799352169036865], f = 7.81975793838501
x = [2.163581371307373, 3.376239776611328, 2.0792925357818604], f = 68.47846984863281
x = [3.2813611030578613, -1.4577455520629883, -0.7837600708007812], f = 28.027585983276367
x = [2.241990566253662, 4.343071937561035, 2.2835428714752197], f = 135.9388427734375
x = [3.730821132659912, -3.319580078125, -4.015127182006836], f = 240.7893524169922
x = [1.8568247556686401, 15.504944801330566, 10.041937828063965], f = 24842.201171875
x = [7.88743782043457, -314.8707275390625, -471.8345642089844], f = 22072229888.0
x = [-119.43834686279297, 14019840.0, 93556

In [63]:
import torch

def f(x):
    return (x[0] - 2*x[1] - 1)**2 + (x[1] - x[2] - 1)**2 + 1


def f_grad(x):
    z = f(x)
    z.backward()
    return x.grad



x = torch.tensor([1., 2., 3.], requires_grad=True)

for i in range(50):
    x = x - 0.1*f_grad(x) 
    x = x.detach().requires_grad_(True)

    print('x = {}, f = {}'.format(x, f(x)))

x = tensor([1.8000, 0.8000, 2.6000], requires_grad=True), f = 9.479999542236328
x = tensor([1.9600, 1.0400, 2.0400], requires_grad=True), f = 6.254400253295898
x = tensor([2.1840, 0.9920, 1.6400], requires_grad=True), f = 4.355903625488281
x = tensor([2.3440, 1.0016, 1.3104], requires_grad=True), f = 3.1475019454956055
x = tensor([2.4758, 0.9997, 1.0486], requires_grad=True), f = 2.374390125274658
x = tensor([2.5805, 1.0001, 0.8388], requires_grad=True), f = 1.8796093463897705
x = tensor([2.6645, 1.0000, 0.6711], requires_grad=True), f = 1.5629498958587646
x = tensor([2.7316, 1.0000, 0.5369], requires_grad=True), f = 1.3602879047393799
x = tensor([2.7853, 1.0000, 0.4295], requires_grad=True), f = 1.2305842638015747
x = tensor([2.8282, 1.0000, 0.3436], requires_grad=True), f = 1.1475739479064941
x = tensor([2.8626, 1.0000, 0.2749], requires_grad=True), f = 1.094447374343872
x = tensor([2.8900, 1.0000, 0.2199], requires_grad=True), f = 1.0604462623596191
x = tensor([2.9120, 1.0000, 0.175